# Generated by Django 5.1.5 on 2025-01-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='myinfo',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
